### ISSUE TITLE
[Watir 6.15] Changes to present? functionality cause page revisits to be unable to locate the page

### ISSUE THREAD

**Issue by PanoramicPanda** [OzFramework/oz#144]
Watir made some changes in 6.14 to how stale/present works, and the updates I've worked out are breaking revisits of pages. I'm making this issue to get some assistance on this and bring the problem to light.

Article on Staleness -[http://watir.com/staleness-changes/](http://watir.com/staleness-changes/)

Created a branch to show the issue: [https://github.com/OzFramework/oz/tree/watir-6.15-present-changes](https://github.com/OzFramework/oz/tree/watir-6.15-present-changes)

`Scenario: Navigate Back to a Previous Page`

**Comment by PanoramicPanda** [comment]
Appears to be a design oversight in Watir. @Castone22 and I have been discussing.

**Comment by Castone22** [comment]
https://github.com/watir/watir/issues/830

**Comment by Castone22** [comment]
Looks like this has been solved now as of watir 6.16.

**Comment by Castone22** [comment]
Going to close this since I applied a monkeypatch that fixes it for now.
