### ISSUE TITLE
Allow manipulation of routes from within page objects

### ISSUE THREAD

**Issue by Castone22** [OzFramework/oz#175]
It may be worthwhile to expose the routes variable in the proceed_to loop so that a page can dynamically set which page it will end up on based on application state.

Proposal would basically be to allow something like
```ruby
some_element.on_fill do
  @world.routes.insert_route(SomePage)
end
```

or 

```ruby
def on_page_load
  @world.routes.insert_route(SomePage) if ledger.get_value(APreviousPage, :visit_some_page_checkbox).eql?('checked')
end
```

This is a natural progression from the proceed_to! solution, which does have several drawbacks
- Recalculation is slow because it's limited by the timeout on page identification.
- It's a bit magical in nature

The reason i'm leaning towards this solution is that it, like most of oz, is declarative, and it continues to encapsulate the knowledge of where pages can route to inside of them.

**Comment by PanoramicPanda** [comment]
I like this idea a lot.

**Comment by Castone22** [comment]
it's actually theoretically done, i'm just making sure it works and i'll persist it up later today.

**Comment by Castone22** [comment]
Theoetically, this also in part falls under the jurisdiction of #41.
