### ISSUE TITLE
Headless Browser

### ISSUE THREAD

**Issue by McAllaster** [OzFramework/oz#60]
Implementing a configuation option to use a headless browser could help with the current developer experience, as well as machine compatibility.

Case 1: Sometimes you might not want to watch the test(s) run, but simply want to observe the logs, and if the test(s) passed/failed.

Case 2: Small screens (or highly scaled ones) might not have enough room to show a complete window, causing a responsive website to change its view).

Case 3: Tiling window managers auto-resizing windows would not be able to interact with a headless browser session. This would avoid any errors caused by responsive web views.

Case 4: We would support terminal-only automation. Setting up a server with a graphical environment can be more resource-intensive than having a headless setup.

**Comment by greenarrowdb** [comment]
Fixed with #61
