### ISSUE TITLE
CLOSE_BROWSER option no longer works.

### ISSUE THREAD

**Issue by greenarrowdb** [OzFramework/oz#64]
Pretty sure the updates to allow chrome to run headlessly have borked the CLOSE_BROWSER option. The browser now always closes, regardless of how the option is set.

**Comment by McAllaster** [comment]
I am unable to reproduce this issue on the current Master branch. What are the watir/chromedriver versions that are being used in the broken case?

**Comment by McAllaster** [comment]
Confirmed to be an issue on single scenarios.

**Comment by greenarrowdb** [comment]
Also seems to be an issue when running multiple scenarios, but only the last browser opened gets closed.

**Comment by greenarrowdb** [comment]
The cause seems to be explained here: https://github.com/watir/watir/issues/523

**Comment by dbwest** [comment]
Just curious on why this was closed. It is still a problem AFAIK, though I guess it is a problem with watir?

**Comment by greenarrowdb** [comment]
I don't want to spend a lot of time trying to fix watir issues. They are already aware of it and will fix it at some point. If it is really a pain then we should escalate with them, not try to monkey patch it here. If we patch it here it will likely not get noticed when Watir eventually does fix it.

**Comment by dbwest** [comment]
Agreed.
