### ISSUE TITLE
Oz doesn't handle hover dropdown/flyout menus

### ISSUE THREAD

**Issue by PanoramicPanda** [OzFramework/oz#85]

**Comment by greenarrowdb** [comment]
Do you have an example of this?

**Comment by PanoramicPanda** [comment]
Example site uses a similar menu style on it's navigation, which Oz gets around by clicking the main header of the bar and then clicking a different link on that page rather than being able to trigger a hover on the parent and then click the child element that appears.

In our AUT, the parent element doesn't link to a page with ways to the child elements, it simply houses the links via the hover.

**Comment by greenarrowdb** [comment]
This sounds more like we need hover functionality rather than 'menu' functionality...

**Comment by PanoramicPanda** [comment]
That would be a good solution, yeah. The title of the issue is still correct however. We could close this and open a solution card instead.

**Comment by greenarrowdb** [comment]
Fixed with #93
